# Generated by Django 5.1.4 on 2025-01-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/gallery')),
                ('title', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'paintings',
                'ordering': ['-year'],
            },
        ),
    ]
