# Generated by Django 5.1.4 on 2025-04-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='alt_image',
            field=models.CharField(default='oil painting'),
        ),
    ]
