# Generated by Django 5.1.4 on 2024-12-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/products')),
                ('image_alt', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subject', models.CharField(choices=[('La', 'Landscape'), ('Se', 'Seascape'), ('St', 'Still life'), ('Fl', 'Flowers')], max_length=100)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Mi', 'Miniature'), ('Pa', 'Painting')], max_length=100)),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
